version: "3"

services:

  server:
    build:
      context: .
      dockerfile: ./serveur/Dockerfile
    ports:
      - "10000:10000"
    networks:
      internalGame:
        ipv4_address: 192.168.2.1
    tty: true
         
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    networks:
      internalGame:
        ipv4_address: 192.168.2.2
    stdin_open: true
    
networks:
  internalGame:
    ipam:
      driver : default
      config:
        -  subnet: 192.168.2.0/24
