version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "10000:10000"
    networks:
      - internalGame
    stdin_open: true
    tty: true
  server:
    build:
      context: .
      dockerfile: ./serveur/Dockerfile
    networks:
      - internalGame     
networks:
  internalGame:
