version: "3"

services:

  server:
    build:
      context: .
      dockerfile: ./serveur/Dockerfile
    ports:
      - "10000:10000"
    networks:
      default:
        ipv4_address: 192.168.2.1
         
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    networks:
      default:
        ipv4_address: 192.168.2.2
    stdin_open: true
    tty: true
    volumes:
      - /dev:/dev
    
networks:
  default:
    ipam:
      driver : default
      config:
        -  subnet: 192.168.2.0/24
           gateway: 192.168.2.254
